on:
  poll:
    url: https://itunes.apple.com/lookup?id=1079395220&country=tw
    deduplicationKey: version
    itemsPath: results
    config:
      filterOutputs:
        trackName: 1
        version: 1
        trackViewUrl: 1
        releaseNotes: 1

jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_NEWS }}
          method: 'POST'
          data: |
            {
              "username": "App Store Update",
              "avatar_url": "https://cdn.discordapp.com/attachments/543454386873958413/777182480267608114/mi0S5wK.jpg",
              "content": "**${{on.poll.outputs.trackName}} ${{on.poll.outputs.version}} 版本已上架 App Store**\n前往商店查看：${{on.poll.outputs.trackViewUrl}}\n\n更新內容：\n<<<${{on.poll.outputs.releaseNotes}}>>>"
            }
