on:
  poll:
    url: https://itunes.apple.com/lookup?id=1079395220&country=tw
    deduplicationKey: version
    itemsPath: results
    config:
      filterOutputs:
        trackName: 1
        version: 1
        trackViewUrl: 1
        releaseNotes: 1

jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEV }}
          DISCORD_USERNAME: App Store Update
          DISCORD_AVATAR: https://cdn.discordapp.com/attachments/543454386873958413/777182480267608114/mi0S5wK.jpg
        uses: Ilshidur/action-discord@master
        with:
          args: |
            **${{on.poll.outputs.trackName}} ${{on.poll.outputs.version}} 版本已上架 App Store**
            前往商店查看：${{on.poll.outputs.trackViewUrl}}
            
            更新內容：
            ${{on.poll.outputs.releaseNotes}}
