on:
  rsshub:
    path: /bilibili/user/dynamic/350845222
    config:
      skipOnError: true
      format: |
        if (item.description) {
          item.content = item.description.replace(/<br\/?>/g, "\n").replace(/<[^>]*>/g, "").trim()
          if (item.content.length > 1000) {
            item.content = `${item.content.substring(0, 997)}...`
          }
        }
        let matchImgs = item.description.match(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()!@:%_\+.~#?&\/\/=]*)/g)
        item.images = matchImgs?.filter(url => /\.(gif|jpe?g|tiff?|png|webp|bmp)$/i.test(url))
        return item

jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Format message
        id: format
        uses: actions/github-script@v4
        with:
          script: |
            const outputs = ${{ toJSON(on.rsshub.outputs) }}
            const format = (item, username, author, footer) => {
              const payload = {
                "username": username,
                "content": `<${item.link}>`,
                "embeds": [
                  {
                    "author": author,
                    "description": item.content,
                    "footer": footer
                  }
                ]
              };
              if (item.images.length > 0) {
                payload["embeds"][0]["image"] = {
                  "url": item.images[0]
                };
                if (item.images.length > 1) {
                  payload["embeds"].push(...item.images.slice(1).map(img => ({
                    "image": {
                      "url": img
                    }
                  })));
                }
              }
              console.log(JSON.stringify(payload));
              return payload;
            };
            return format(outputs, "万象物语的个人空间 - 哔哩哔哩 ( ゜- ゜)つロ 乾杯~ Bilibili", {
              "name": "万象物语",
              "url": "https://space.bilibili.com/350845222",
              "icon_url": "https://cdn.discordapp.com/attachments/543454386873958413/778648876151865364/3065befd98a6a1a5e513ef8aa3309636716f0f96.png"
            }, {
              "text": "Bilibili",
              "icon_url": "https://cdn.discordapp.com/attachments/543454386873958413/778648632127127613/39107515-619773e0-46f5-11e8-9fa9-2859816f1c42.png"
            })
      - name: Discord notification
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_NEWS_FEED }}
          method: 'POST'
          data: ${{ steps.format.outputs.result }}
