on:
  rss:
    url: https://rsshub.app/bilibili/user/dynamic/350845222
    config:
      # skipFirst: true

jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Format message
        id: format
        uses: actions/github-script@v2
        with:
          script: |
            const outputs = ${{ toJSON(on.rss.outputs) }};
            const payload = {
              "username": "万象物语的个人空间 - 哔哩哔哩 ( ゜- ゜)つロ 乾杯~ Bilibili",
              "content": `<${outputs.link}>`,
              "embeds": [{
                "author": {
                  "name": "万象物语",
                  "url": "https://space.bilibili.com/350845222",
                  "icon_url": "https://cdn.discordapp.com/attachments/543454386873958413/778648876151865364/3065befd98a6a1a5e513ef8aa3309636716f0f96.png"
                },
                "description": outputs.contentSnippet,
                "footer": {
                  "text": "Bilibili",
                  "icon_url": "https://cdn.discordapp.com/attachments/543454386873958413/778648632127127613/39107515-619773e0-46f5-11e8-9fa9-2859816f1c42.png"
                }
              }]
            };
            let matchImgs = outputs.content.match(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()!@:%_\+.~#?&\/\/=]*)/g);
            matchImgs = matchImgs && matchImgs.filter(url => url.endsWith('.png') || url.endsWith('.jpg'));
            if (matchImgs && matchImgs.length > 0) {
              payload["embeds"][0]["image"] = {
                "url": matchImgs[0]
              };
            }
            return payload;
      - name: Discord notification
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_DEV }}
          method: 'POST'
          data: ${{ steps.format.outputs.result }}
