on:
  facebook:
    page: rayark.sdorica
    config:
      # skipFirst: true
      format: |
        if (item.content) {
          item.content = item.content.trim()
          if (item.content.length > 1000) {
            item.content = `${item.content.substring(0, 997)}...`
          }
        }
        return item

jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Format message
        id: format
        uses: actions/github-script@v4
        with:
          script: |
            const outputs = ${{ toJSON(on.rsshub.outputs) }}
            const format = require('./actions/discord-format.js')
            return format(outputs, "Sdorica | Facebook", {
              "name": "Sdorica (@rayark.sdorica)",
              "url": "https://www.facebook.com/rayark.sdorica/",
              "icon_url": "https://cdn.discordapp.com/attachments/543454386873958413/777186584000724992/118745707_1600182993519599_5578732041796140826_o.png"
            }, {
              "text": "Facebook",
              "icon_url": "https://cdn.discordapp.com/attachments/543454386873958413/777182912629309480/m8bb1q5.png"
            })
      - name: Discord notification
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_NEWS_FEED }}
          method: 'POST'
          data: ${{ steps.format.outputs.result }}
      - name: Discord notification
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_GAMECHAT }}
          method: 'POST'
          data: ${{ steps.format.outputs.result }}
