on:
  facebook:
    page: rayark.sdorica
    config:
      lang: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6
      # skipFirst: true

jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_DEV }}
          method: 'POST'
          data: |
            {
              "username": "Sdorica Facebook",
              "content": "<${{on.facebook.outputs.link}}>",
              "embeds": [{
                "author": {
                  "name": "Sdorica (@rayark.sdorica)",
                  "url": "https://www.facebook.com/rayark.sdorica/",
                  "icon_url": "https://cdn.discordapp.com/attachments/543454386873958413/777186584000724992/118745707_1600182993519599_5578732041796140826_o.png"
                },
                "description": "<<<${{on.facebook.outputs.content}}>>>",
                "footer": {
                  "text": "Facebook",
                  "icon_url": "https://cdn.discordapp.com/attachments/543454386873958413/777182912629309480/m8bb1q5.png"
                }
              }]
            }
