on:
  rss:
    url: https://gnn.gamer.com.tw/rss.xml
    config:
      filter:
        $or:
        - title:
            $regex: sdorica
            $options: i
        - contentSnippet:
            $regex: sdorica
            $options: i
      filterOutputs:
        title: 1
        link: 1

jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_DEV }}
          method: 'POST'
          data: |
            {
              "username": "GNN新聞",
              "avatar_url": "https://cdn.discordapp.com/attachments/543454386873958413/777182478410317834/jcseAjD.png",
              "content": "${{on.rss.outputs.title}}\n${{on.rss.outputs.link}}"
            }
